const images = {
  otherActivities: {
    photography: require('src/assets/images/other-activities/tahsin-nikon-z50.jpg').default,
    books: require('src/assets/images/other-activities/book-with-coffee.jpg').default,
    movies: require('src/assets/images/other-activities/movie-pop-corn.jpg').default,
    music: require('src/assets/images/other-activities/music-concert.jpg').default,
    travel: require('src/assets/images/other-activities/plane.jpg').default,
  },
  logogs: {
    work: {
      halojasa: require('src/assets/images/logos/resized/halojasa-logo.png').default,
      teras: require('src/assets/images/logos/resized/teraswork-logo.jpg').default,
      bountie: {
        withCaption: require('src/assets/images/logos/resized/bountie-logo-with-caption.png').default,
        justLogo: require('src/assets/images/logos/resized/bountie-io-logo.png').default,
      },
    },
    telegram: require('src/assets/images/logos/resized/telegram-logo.png').default,
    discord: require('src/assets/images/logos/resized/Discord-Logo-Square-1024x1024.png').default,
    linkedIn: require('src/assets/images/logos/resized/linkedin-logo.png').default,
    twitter: require('src/assets/images/logos/resized/twitter-logo.png').default,
    npm: require('src/assets/images/logos/resized/npm-2-logo-svg-vector.png').default,
    pypi: require('src/assets/images/logos/resized/pypi-logo.png').default,
    medium: require('src/assets/images/logos/resized/medium-icon-white-on-black.png').default,
    keybase: require('src/assets/images/logos/resized/Keybase_logo_official.png').default,
    git: require('src/assets/images/logos/resized/git-logo.png').default,
    gitLab: require('src/assets/images/logos/resized/gitlab-icon-rgb.png').default,
    gitHub: require('src/assets/images/logos/resized/github-logo.png').default,
    facebook: require('src/assets/images/logos/resized/Facebook_icon_2013.svg.png').default,
    instagram: require('src/assets/images/logos/resized/instagram-logo.png').default,
    digitalOcean: require('src/assets/images/logos/resized/digitalocean_logo_icon_169273.png').default,
    devTo: require('src/assets/images/logos/resized/dev-black.png').default,
    grpc: require('src/assets/images/logos/resized/grpc.png').default,
    database: require('src/assets/images/logos/resized/databases-logo.png').default,
    gitHubActions: require('src/assets/images/logos/resized/github-actions-logo.png').default,
    docker: require('src/assets/images/logos/resized/docker-logo.png').default,
    firebase: require('src/assets/images/logos/resized/firebase_logo.png').default,
    googlePubSub: require('src/assets/images/logos/resized/google-pub-sub.png').default,
    gulp: require('src/assets/images/logos/resized/gulp-logo.jpg').default,
    hashicorpVault: require('src/assets/images/logos/resized/hashicorp-vault-logo.png').default,
    jasmine: require('src/assets/images/logos/resized/jasmine-logo.png').default,
    jest: require('src/assets/images/logos/resized/jest-logo.jpg').default,
    doppler: require('src/assets/images/logos/resized/doppler.webp').default,
    opsManager: require('src/assets/images/logos/resized/ops_manager_backup.png').default,
    redis: require('src/assets/images/logos/resized/redis-logo.png').default,
    redux: require('src/assets/images/logos/resized/redux-logo.png').default,
    reduxSaga: require('src/assets/images/logos/resized/redux-saga-logo.png').default,
    sass: require('src/assets/images/logos/resized/sass-logo.png').default,
    selenium: require('src/assets/images/logos/resized/selenium-logo.png').default,
    socketIO: require('src/assets/images/logos/resized/socket-io-logo.png').default,
    sonarQube: require('src/assets/images/logos/resized/sonarqube-logo.png').default,

    programmingLanguages: {
      go: require('src/assets/images/logos/resized/go-programming-language.png').default,
      typescript: require('src/assets/images/logos/resized/typescript-logo.png').default,
      java: require('src/assets/images/logos/resized/java-logo.png').default,
      python: require('src/assets/images/logos/resized/python-logo.png').default,
      javascript: require('src/assets/images/logos/resized/javascript-logo.png').default,
      bash: require('src/assets/images/logos/resized/bash-logo.png').default,
    },
  },
};

export default images;
