const images = {
  gifs: {
    loadingBar: require('src/assets/gifs/Loading-bar.gif').default,
    iPhoneSpinner: require('src/assets/gifs/iPhone-spinner.gif').default,
  },

  otherActivities: {
    photography: require('src/assets/images/other-activities/tahsin-nikon-z50.jpg').default,
    books: require('src/assets/images/other-activities/book-with-coffee.jpg').default,
    movies: require('src/assets/images/other-activities/movie-pop-corn.jpg').default,
    music: require('src/assets/images/other-activities/music-concert.jpg').default,
    travel: require('src/assets/images/other-activities/plane.jpg').default,
  },
  logogs: {
    work: {
      halojasa: require('src/assets/images/logos/halojasa-logo.png').default,
      teras: require('src/assets/images/logos/teraswork-logo.jpg').default,
      bountie: {
        withCaption: require('src/assets/images/logos/bountie-logo-with-caption.png').default,
        justLogo: require('src/assets/images/logos/bountie-io-logo.png').default,
      },
    },
    telegram: require('src/assets/images/logos/telegram-logo.png').default,
    discord: require('src/assets/images/logos/Discord-Logo-Square-1024x1024.png').default,
    linkedIn: require('src/assets/images/logos/linkedin-logo.png').default,
    twitter: require('src/assets/images/logos/twitter-logo.png').default,
    npm: require('src/assets/images/logos/npm-2-logo-svg-vector.png').default,
    pypi: require('src/assets/images/logos/pypi-logo.png').default,
    medium: require('src/assets/images/logos/medium-icon-white-on-black.png').default,
    keybase: require('src/assets/images/logos/Keybase_logo_official.png').default,
    git: require('src/assets/images/logos/git-logo.png').default,
    gitLab: require('src/assets/images/logos/gitlab-icon-rgb.png').default,
    gitHub: require('src/assets/images/logos/github-logo.png').default,
    facebook: require('src/assets/images/logos/Facebook_icon_2013.svg.png').default,
    instagram: require('src/assets/images/logos/instagram-logo.png').default,
    digitalOcean: require('src/assets/images/logos/digitalocean_logo_icon_169273.png').default,
    devTo: require('src/assets/images/logos/dev-black.png').default,
    grpc: require('src/assets/images/logos/grpc.png').default,
    database: require('src/assets/images/logos/databases-logo.png').default,
    gitHubActions: require('src/assets/images/logos/github-actions-logo.png').default,
    docker: require('src/assets/images/logos/docker-logo.png').default,
    firebase: require('src/assets/images/logos/firebase_logo.png').default,
    googlePubSub: require('src/assets/images/logos/google-pub-sub.png').default,
    gulp: require('src/assets/images/logos/gulp-logo.jpg').default,
    hashicorpVault: require('src/assets/images/logos/hashicorp-vault-logo.png').default,
    jasmine: require('src/assets/images/logos/jasmine-logo.png').default,
    jest: require('src/assets/images/logos/jest-logo.jpg').default,
    doppler: require('src/assets/images/logos/doppler.webp').default,
    opsManager: require('src/assets/images/logos/ops_manager_backup.png').default,
    redis: require('src/assets/images/logos/redis-logo.png').default,
    redux: require('src/assets/images/logos/redux-logo.png').default,
    reduxSaga: require('src/assets/images/logos/redux-saga-logo.png').default,
    sass: require('src/assets/images/logos/sass-logo.png').default,
    selenium: require('src/assets/images/logos/selenium-logo.png').default,
    socketIO: require('src/assets/images/logos/socket-io-logo.png').default,
    sonarQube: require('src/assets/images/logos/sonarqube-logo.png').default,

    programmingLanguages: {
      go: require('src/assets/images/logos/go-programming-language.png').default,
      typescript: require('src/assets/images/logos/typescript-logo.png').default,
      java: require('src/assets/images/logos/java-logo.png').default,
      python: require('src/assets/images/logos/python-logo.png').default,
      javascript: require('src/assets/images/logos/javascript-logo.png').default,
      bash: require('src/assets/images/logos/bash-logo.png').default,
    },
  },
};

export default images;
