#!/usr/bin/env node

const cp = require('child_process');
const fs = require('fs');
const path = require('path');

cp.execSync('yarn build', { stdio: 'inherit' });

const clientBuildDir = path.join(process.cwd(), 'build');
const serverPublicDir = path.join(process.cwd(), '..', 'server', 'public');

const files = fs.readdirSync(clientBuildDir);

if (fs.existsSync(serverPublicDir)) {
  fs.rmdirSync(serverPublicDir, { recursive: true });
}
fs.mkdirSync(serverPublicDir);

files.forEach(file => {
  fs.renameSync(`${clientBuildDir}/${file}`, `${serverPublicDir}/${file}`);
});

console.log(`Moved dist dir to ${serverPublicDir}`);
