version: "3"

services:
  app:
    image: tahsinature/me:1
    networks: [traefik]
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`tahsin.us`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=myresolver

networks:
  traefik:
    external: true
