version: '3.9'

services:
  frontend:
    container_name: web
    build:
      context: .
      dockerfile: custom.dev.dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
