version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: custom.prod.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ~/Workstation/personal/me/src:/app/src
      - ~/Workstation/personal/me/public:/app/public
    network_mode: host
    command: npm start
