version: "3"

services:
  tahsinus-front:
    container_name: tahsin.us
    image: tahsinature/me-front:latest
    networks: [traefik]
    labels:
      - traefik.enable=true
      - traefik.http.routers.tahsinus-front.rule=Host(`tahsin.us`)
      - traefik.http.services.tahsinus-front.loadbalancer.server.port=80
      - traefik.http.routers.tahsinus-front.tls=true
      - traefik.http.routers.tahsinus-front.entrypoints=websecure
      - traefik.http.routers.tahsinus-front.tls.certresolver=myresolver

  tahsinus-back:
    container_name: back.tahsin.us
    image: tahsinature/me-back:latest
    networks: [traefik]
    volumes:
      - ./scripts:/app/get-env
    environment:
      DOPPLER_TOKEN: $DOPPLER_TOKEN_MY_PERSONAL
      DOPPLER_PROJECT: tahsin-us-back
      DOPPLER_CONFIG: prd
    entrypoint: sh -c './get-env && ./app -r'
    labels:
      - traefik.enable=true
      - traefik.http.routers.tahsinus-back.rule=Host(`back.tahsin.us`)
      - traefik.http.services.tahsinus-back.loadbalancer.server.port=3001
      - traefik.http.routers.tahsinus-back.tls=true
      - traefik.http.routers.tahsinus-back.entrypoints=websecure
      - traefik.http.routers.tahsinus-back.tls.certresolver=myresolver

networks:
  traefik:
    external: true
