version: "3.9"

services:
  db:
    image: postgres:14.1-alpine3.14
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./scripts/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ./scripts/extension.sql:/docker-entrypoint-initdb.d/extension.sql
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME

  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - ./scripts:/app/scripts
      - ./.env:/app/.env
      - /app/bin
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: sh -c './scripts/wait-for -t 30 db:5432 redis:6379 -- make run-watch'
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./scripts:/app/scripts
    depends_on:
      - backend
    command: sh -c './scripts/wait-for -t 900 backend:3001 -- npm start'
    ports:
      - "3000:3000"
