version: "3"

services:
  tahsinus:
    container_name: back.tahsin.us
    image: tahsinature/me-back:latest
    networks: [traefik]
    volumes:
      - ./scripts/doppler:/app/get-env
    environment:
      DOPPLER_TOKEN: $DOPPLER_TOKEN_MY_PERSONAL
      DOPPLER_PROJECT: tahsin-us
      DOPPLER_CONFIG: prd
    entrypoint: sh -c './get-env && ./main -r'
    labels:
      - traefik.enable=true
      - traefik.http.routers.tahsinus-back.rule=Host(`tahsin.us`)
      - traefik.http.services.tahsinus-back.loadbalancer.server.port=3001
      - traefik.http.routers.tahsinus-back.tls=true
      - traefik.http.routers.tahsinus-back.entrypoints=websecure
      - traefik.http.routers.tahsinus-back.tls.certresolver=myresolver

networks:
  traefik:
    external: true
