// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID        string   `json:"id"`
	Title     string   `json:"title"`
	Year      int      `json:"year"`
	MyRating  string   `json:"myRating"`
	Genres    []string `json:"genres"`
	Image     string   `json:"image"`
	WatchedAt string   `json:"watchedAt"`
}
