version: "3.9"

services:
  db:
    image: postgres:14.1-alpine3.14
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./scripts/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ./scripts/extension.sql:/docker-entrypoint-initdb.d/extension.sql
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME

  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/bin
    depends_on:
      - db
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: sh -c './scripts/wait-for db:5432 redis:6379 -- air'
    ports:
      - "9000:9000"
