version: '3.9'

services:
  me-server:
    build:
      context: .
      dockerfile: custom.prod.dockerfile
    environment:
      VIRTUAL_PORT: '3001'
      VIRTUAL_HOST: 'me-server.do.tahsinature.me'
      LETSENCRYPT_HOST: 'me-server.do.tahsinature.me'
    networks:
      - nginx_proxy_net

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/dev/redis:/data
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    networks:
      - nginx_proxy_net

networks:
  nginx_proxy_net:
    external: true
