const flags = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_QUERY_PARAM: 'INVALID_QUERY_PARAM',
  INVALID_URL: 'INVALID_URL',
  INVALID_URL_PARAM: 'INVALID_URL_PARAM',
  INVALID_HEADER: 'INVALID_HEADER',
  SOCKET_CONNECTION_NOT_FOUND: 'SOCKET_CONNECTION_NOT_FOUND',
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  NOT_ADMIN: 'NOT_ADMIN',
  INVALID_FCM_TOKEN: 'INVALID_FCM_TOKEN',
}

export default flags
