name: ci

on: [push]

jobs:
  primary-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (Frontent)
        uses: docker/build-push-action@v2
        with:
          context: ../client
          push: true
          tags: tahsinature/me-front:1
      - name: Build and push (Backend)
        uses: docker/build-push-action@v2
        with:
          context: ../server
          push: true
          tags: tahsinature/me-back:1
