name: ci

on:
  push:
    branches:
      - "master"

jobs:
  # frontend-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push (Frontent)
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./client
  #         push: true
  #         tags: tahsinature/me-front:latest

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (Backend)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tahsinature/me-back:latest
